### ISSUE TITLE
Stitiching n views out of m as tif saves without transformation

### ISSUE THREAD

**Issue by kapoorlab** [PreibischLab/BigStitcher#112]
Hi,

After doing the registration I save the project as xml and h5 and then I try to save only a single view as a tiff but after it is saved it does not has the applied transformation and is saved without it, in the BDV I can see the views as perfectly stitched but when I see the tiff files of the views I just stitched I see them as if no affine transformation was applied on the view that I did. 

I am clicking on resave dataset option in the stitching panel, is there a way to save the selected view as tif with the transformation applied to it?

**Comment by hoerldavid** [comment]
Hi Varun,

When you use resave, it will just resave the raw data files, not create an aligned version.
You would have to do a fusion (https://imagej.net/plugins/bigstitcher/fuse). If you only want to transform a single image, you can just select that one image and "fuse" it.

Best,
David

**Comment by kapoorlab** [comment]
Hi David, So just to make sure that the fusion option does not actually show up in the multiview mode, I have to switch to stitching mode and then get the image fusion option and then save the fused view which in this case is the registration right?

**Comment by hoerldavid** [comment]
It should be in the right-click menu in both modes, but at different locations:
* ```Fusion -> Image Fusion ...``` in Stitching mode
* ```Processing -> Image Fusion ...``` in Multiview mode

**Comment by kapoorlab** [comment]
Ah yes it is indeed present in both modes, I found it in both and it saves the transformed data as expected. Thanks!
