### ISSUE TITLE
File loading - allow tiles to be read from filename by axis subscript

### ISSUE THREAD

**Issue by alonyan** [PreibischLab/BigStitcher#12]
Thank you guys for this very impressive work. It's invaluable.

I'm dealing with a fairly large set of stacks. The current acquisition setup generates a filename with the pattern: ..._X3_Y2_... where the numbers correspond to a specific tile's subscripts. Currently, when loading the data, only the tile "index" can be used and using both the subscripts at "tiles" results in a loading error. 

Would it be possible to implement a {subx} ,{suby}... option in the loading that automatically reads subscripts instead of indexes?

Thanks again!

**Comment by hoerldavid** [comment]
Hi @alonyan,

It should be possible to select two patterns to represent Tiles:

![image](https://user-images.githubusercontent.com/3527592/36901202-a2b88c12-1e26-11e8-9d82-5797307c4e94.png)

This is working for me for a simple TIFF dataset. What format are the files you are working with?

Could you provide us with:
* the error log (console output) when it crashes as you try to load your data
* (if it is not too big) a small subset of your data (just 2x2 tiles or so) so we can try to fix the bug if it persists.

Cheers,
David

**Comment by alonyan** [comment]
Hi David,

Sorry, should have closed this a while ago. The problem was actually in another place, the filenames had the channel number & name (...Ch01_Green...) and that caused problems. Changed things on the acquisition side and everything works. Only problem now is that the expected runtime to process a full experiment will be over a month.

Thanks again!
Alon
