### ISSUE TITLE
BigStitcher batch processing launches a new Fiji window

### ISSUE THREAD

**Issue by dpshepherd** [PreibischLab/BigStitcher#121]
Hi all-

With the most recent update, a new Fiji window is created upon launching "calculate pairwise shifts" in batch processing mode. We replicated this behavior on Ubuntu 20.04, Windows 10, and Windows 11. The second Fiji process has to be closed through task manager (Windows) or processed killed.

This also prevents batch processing from the command line in `--headless` mode.

To replicate:
1. Update BigStitcher to most recent update
2. Launch Fiji
3. Launch BigStitcher->Batch Processing-> Calculate Pairwise Shifts

You can keep creating new Fiji windows by repeating the above in the active Fiji window. Almost inception like...

Thanks again for the awesome tool!
Doug

**Comment by sommerc** [comment]
Same here. On Windows 10 and Debian Linux.

**Comment by ctrueden** [comment]
I'm guessing the problem is caused by 29a1cb647c630cb823827a44fd1d2e85afe70bef, specifically the addition of `new ImageJ()` in the `Calculate_Pairwise_Shifts` plugin's `run` method. @StephanPreibisch Is this a mistake, left over from debugging?

**Comment by ctrueden** [comment]
Testing locally confirmed that removal of the `new ImageJ()` code fixes the issue, so I pushed the fix.

**Comment by dpshepherd** [comment]
Thank you @ctrueden !

**Comment by StephanPreibisch** [comment]
upsi, my bad. Thanks so much @ctrueden

**Comment by StephanPreibisch** [comment]
And Fiji is updated ...

**Comment by StephanPreibisch** [comment]
Thanks everyone!!

**Comment by lguerard** [comment]
Can confirm that the update directly from Fiji fixed it as expected. Thanks a lot both :)
