### ISSUE TITLE
Recent Fiji update broke Image Fusion

### ISSUE THREAD

**Issue by Eddymorphling** [PreibischLab/BigStitcher#128]
Hi all,
After upgrading to the latest version build of Fiji, BigStitcher gives an error message when performing an Image Fusion. The error message is the same as mentioned in this ImageJ forum post - https://forum.image.sc/t/bigstitcher-stopped-fusion-after-latest-imagej-update/83606. Everything worked well till last week.

I believe its connected to the ImgLib2? Any idea what could be the issue here? Thanks.

**Comment by StephanPreibisch** [comment]
Hi @Eddymorphling, thanks so much for reporting. I have actually been waiting for Fiji to update to the newest version so I can push this update and I just did. I think everything should work now again. You'll also see some improvements around the software I believe ...
