### ISSUE TITLE
Fusion to 2D TIFF series

### ISSUE THREAD

**Issue by adamkglaser** [PreibischLab/BigStitcher#17]
Hello,

BigStitcher is absolutely amazing and is producing beautiful results with our data.  If possible, my one request would be an option to fuse results to a 2D TIFF series rather than multipage TIFF.

Thanks!
Adam

**Comment by hoerldavid** [comment]
Hi @adamkglaser ,

This should be possible already.
In the Fusion Dialog, just select ```Display using ImageJ```. Once the fused Image pops up as an ImageJ window, you can go to ```File -> Save As -> Image Sequence...``` to save every slice as a separate file.

On a side Note: you can use this procedure to save fused images that are larger than your available RAM, if you select ```Virtual``` or ```Cached``` Fusion. That way, we only fuse plane-by-plane and save immediately.

We could of course add the saving as 2D TIFFs to the fusion dialog directly - what are your thoughts on this @StephanPreibisch ?

All the best,
David

**Comment by adamkglaser** [comment]
Thanks, this will work for us.  One additional question is regarding the
fusion methods (in memory vs. virtual vs. cached).  Is there is a
significant speed difference between the methods (i.e., is in memory much
faster?).  I see the suggestion that virtual is better performance for TIFF
fusion and cached is better performance for HDF5 fusion.

Adam

**Comment by StephanPreibisch** [comment]
Hi @adamkglaser, if your only goal is to save it, it doesn't make much of a difference and I would choose virtual ...
