### ISSUE TITLE
Fusion - downsampling - resulting pixel size

### ISSUE THREAD

**Issue by schmiedc** [PreibischLab/BigStitcher#2]
Hi :)

just to clarify, when I perform the fusion of the stitched data using "Fuse image(s)".
I apply a downsampling of 4. Then as far as I checked xy get downsampled by that number.
However z then only by a factor of 2. Is this correct? 

It would be really really really great to write the correct xyz pixel size into the resulting .tif file. 

Thank you!
Christopher

**Comment by hoerldavid** [comment]
Hi Christopher,

I assume the raw z pixel size of your data is twice the xy pixel size?
At the moment, the fusion generates an image with isotropic pixel size (like in the Multiview Reconstruction).

Stephan and I have already discussed this problem and we will make the fusion use the same pixel size as the raw data in cases where we have just stitching of one angle.
Expect that in one of the next updates :)

We will also set the pixel size in the properties of the generated TIFFs.

Cheers,
David
