### ISSUE TITLE
Fused ImagePlus images lack calibration 

### ISSUE THREAD

**Issue by bogovicj** [PreibischLab/BigStitcher#21]
After:
1) `Image Fusion...`
2) `Fused Image: Display using imageJ`

The resulting `ImagePlus`'s are uncalibrated. i.e. Pixel width/heigh/depth are all 1.0 pixel

**Comment by StephanPreibisch** [comment]
thanks @bogovicj for realizing, will fix it soon!

**Comment by StephanPreibisch** [comment]
Just realized that the calibration will in most cases be approximate since it of course depends on the individual registrations of each view. Except for translation-only, there will always be small inconsistencies, or even large ones if the alignment is not correct.

**Comment by bogovicj** [comment]
True, calibration is meaningless in the case of scaling, though maybe something is better than nothing..?

I'll understand if you decide to not to have this since it won't work in the general case. But maybe something like an "Infer calibration" feature will help in the most often used cases?

ps. this was my first time using Bigstitcher for something real (small, but real) - love it.
Thanks @StephanPreibisch  and @hoerldavid

**Comment by StephanPreibisch** [comment]
Should be fixed with commit https://github.com/PreibischLab/multiview-reconstruction/commit/519a2c56d93d99592840b30e65dc5eac5ce888af

**Comment by StephanPreibisch** [comment]
we are still waiting for the reviews to come in before updating it on Fiji ... should be soon
