### ISSUE TITLE
set filename for fusion results

### ISSUE THREAD

**Issue by StephanJanosch** [PreibischLab/BigStitcher#33]
We would like to see the possibility to set the filename of the fusion. Right now we end up always with fused_tp_0_ch_0.tif(.zip) 

That's not cool having dozens of files with the same name.

**Comment by StephanPreibisch** [comment]
Sorry for the delay, fixed with commits:
https://github.com/PreibischLab/multiview-reconstruction/commit/48623c325241834993a7ba42458280d5ea3f027a
https://github.com/PreibischLab/multiview-reconstruction/commit/37b7deaa87aabb87e326a62295634fe3c0c2cc53

Will be there with the next release ...
