### ISSUE TITLE
Why is BigStitcher version stuck at 0.2.10 in Fiji?

### ISSUE THREAD

**Issue by lollopus** [PreibischLab/BigStitcher#44]
I've seen an older thread mentioning problems with the update site not offering the latest version of this plugin (currently at 0.3.10). That was back in 2017-18. What is going on? Is there another update site that we can use?

**Comment by StephanPreibisch** [comment]
Hi, many things changed, I'll do a release soon!

**Comment by StephanPreibisch** [comment]
Hi, new version is uploaded. Contains many bugfixes and exciting new features including quality estimation, dataset splitting and non-rigid alignment.
