### ISSUE TITLE
Auto-color different angles in MultiView Mode

### ISSUE THREAD

**Issue by nelas** [PreibischLab/BigStitcher#45]
Hello,

One feature from the Multiview Reconstruction plugin that I miss the most when using BigStitcher is the auto-coloring of different angles. When two (or more) angles are selected in the Multiview Reconstruction application they get different colors, but this does not happen in the MultiView Mode of BigStitcher. And, if I set the colors manually, they are not persistent (eg colors are lost when clicking on a different view). Auto-coloring is quite handy to check for the registration quality. Any chance this might be implemented back in BigStitcher?

Cheers,
Bruno

**Comment by hoerldavid** [comment]
Hi @nelas,

The feature is still there, actually. When in multiview-mode:

Select the BigStitcher main window (not BigDataViewer) and press the ```c```-key.

Now all Angles and Illumination Directions should receive their own color (but individual Tiles within them should be colored the same). Pressing ```c``` again switches back to greyscale mode.

Best,
David

**Comment by nelas** [comment]
Oh! Great, it works. Thanks, David!
