### ISSUE TITLE
Calculate Pairwise Shifts Crash when Canceled

### ISSUE THREAD

**Issue by iomega15** [PreibischLab/BigStitcher#6]
This problem occurs when I try to cancel out of "Calculate Pairwise Shifts"
https://www.dropbox.com/s/r35a574a8mn0q2y/cancel_stitching.tif?dl=0

Also, I am wondering two things:
1) Is there an "Ignore Zeros" option in BigSticher?
2) How can I simply obtain the equivalent of TileConfiguration.txt from BigStitcher?  All I want is the registered coordinates of the tiles.  Instead it generates a very complex XML, and the number of <affine> and <shifts> entries is much greater than the number of tiles.  So we don't know which ones to use....  
Thanks.

**Comment by StephanPreibisch** [comment]
Hi, we'll check it out and soon have a fix for number 2. What do you mean with - Is there an "Ignore Zeros" option in BigSticher?

**Comment by StephanPreibisch** [comment]
![cancel_stitching_preview](https://user-images.githubusercontent.com/1420587/31214698-c63c488e-a9ac-11e7-8408-d68e5f7e2961.jpeg)

This is the image from the dropbox link above

**Comment by imagejan** [comment]
@StephanPreibisch see also https://github.com/fiji/Stitching/issues/51

**Comment by iomega15** [comment]
Hello, @StephanPreibisch , here is the option I am talking about:
![image](https://user-images.githubusercontent.com/5264699/31234957-3810e616-a9be-11e7-84dd-2a4fee793fb9.png)
Our images are collected under an angle: https://www.intelligent-imaging.com/wp-content/uploads/2016/06/LatticeLS_Excitation_Gr_960x546.png
As a result, our 3D stackis have a Rhombohedron shape that contains zeros on the sides:
![image](https://user-images.githubusercontent.com/5264699/31235107-95cd7c1a-a9be-11e7-9a61-a1c3ea39ccc8.png)
Therefore, the Ignore Zero Values option would be useful for getting the TileConfiguration.txt (we fuse them externally, so only the stitching matters).  But I am not finding it in BigStitcher.  Is it there?  Thanks.

**Comment by StephanPreibisch** [comment]
Hi, for the stitching zeros cannot be ignored, just for the fusion. So it is a useful option, but doesn't change anything in your case if you fuse it externally. Right?

**Comment by iomega15** [comment]
I guess not.  Turns out it was actually the "check peaks" option that made our stitching successful in the pair-wise stitcher.  Since the BigStitcher has that too, we should be good with your hack for the TileConfiguration.txt  Thanks.
