### ISSUE TITLE
export to hdf5 insanely slow

### ISSUE THREAD

**Issue by martinschorb** [PreibischLab/BigStitcher#68]
Hi,

I am trying to export a stitch of individual 2D tif tiles. Each is only 2048x2048 pixels. Export to hdf5 takes more than one minute per file on an 8 core Xeon workstation with massive RAM.

What could be wrong here?

**Comment by StephanPreibisch** [comment]
Hi, please provide more details ...

**Comment by StephanPreibisch** [comment]
Ideally screenshots, logs, etc so I can understand what is going on

**Comment by martinschorb** [comment]
Hi,

to be sure it is not due to a messed-up Fiji installation I did:

- download virgin Fiji
- update the two rounds it needed to be happy
- enable BigStitcher update site, install plugin
- load the project xml (the one still linking to the tifs)
[dataset.xml.zip](https://github.com/PreibischLab/BigStitcher/files/4370404/dataset.xml.zip)
- run "Resave dataset" -> as hdf5
- this takes about one minute per tile...
```Saved XML 'B:/schorb/data/BDV/montages/mont//dataset.xml'.
HDF5 file: B:\schorb\data\BDV\montages\mont\dataset.h5
proccessing timepoint 1 / 1
proccessing setup 1 / 18
Mon Mar 23 16:46:21 CET 2020: Reading image data from 'm10000.tif' [2048x2048x1 angle=0 ch=0 illum=0 tp=0 tile=0 type=uint16 img=ArrayImg<UnsignedShortType>]
writing level 0
writing level 1
writing level 2
writing level 3
proccessing setup 2 / 18
Mon Mar 23 16:47:20 CET 2020: Reading image data from 'm10001.tif' [2048x2048x1 angle=0 ch=0 illum=0 tp=0 tile=1 type=uint16 img=ArrayImg<UnsignedShortType>]
...
```

- For some tiles it comes up with an error:

```
image data for timepoint 0 setup 1 level 2 could not be found. Partition file missing?
```
- this leads to that tile missing in the resulting hdf5, even though it is shown nicely in BigStitcher before (when loading from tif)

![Bigstitcher1](https://user-images.githubusercontent.com/35071867/77335441-6e9a1d00-6d26-11ea-8d82-cbfc17ee1f8d.PNG)

- tifs are here: https://oc.embl.de/index.php/s/ts9V9oPYU0PiFmO

**Comment by martinschorb** [comment]
this is what I get after the export:

- the two tiles are gone, as they are missing in the hdf5. 

![Bigstitcher2](https://user-images.githubusercontent.com/35071867/77337009-9db18e00-6d28-11ea-9114-54f3d2ae4589.PNG)

- This BDV I got from just displaying the tiles from the list in the BigStitcher window that was still open without reloading anything.

- In the previous run, the missing tiles were different ones.

**Comment by StephanPreibisch** [comment]
Hi, there is a bug in the suggesting the block sizes for the resave. Fixed with commit https://github.com/PreibischLab/multiview-reconstruction/commit/15a4ea931f75afb13ef36740fb4449291831dd91

**Comment by StephanPreibisch** [comment]
and https://github.com/PreibischLab/multiview-reconstruction/commit/e1b4c6acca9ebb688711b9e395cafb04c13d0208

**Comment by StephanPreibisch** [comment]
And now the patch it uploaded to Fiji, just update and it should work

**Comment by StephanPreibisch** [comment]
<img width="1394" alt="Screen Shot 2020-03-23 at 4 59 31 PM" src="https://user-images.githubusercontent.com/1420587/77362696-c1c09f80-6d27-11ea-9710-6dda40efb284.png">

**Comment by StephanPreibisch** [comment]
I close the issue for now, if you still have issues I'll open it again. Best, Stephan
