### ISSUE TITLE
Error while calculating pairwise shifts with dataset saved as compressed N5

### ISSUE THREAD

**Issue by HugoB** [PreibischLab/BigStitcher#71]
Hello, 

Using the dataset Grid_2d and the stitching steps provided on the BigStitcher page (https://imagej.net/BigStitcher), I have the following error in the console window when I want to stitch the dataset (during the calculation of the pairwise shifts) saved with the N5 format : 
![ErrorStitchingN5](https://user-images.githubusercontent.com/55397182/80224082-8298ad80-8649-11ea-9a28-f138b737b34a.PNG)

And the associated message in the Log window : 

> Failed to compute pairwise shift: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: not implemented yet

It works when I run it with the dataset saved with the HDF5 format.

**Comment by StephanPreibisch** [comment]
Hi, sorry for the delay, the GitHub message went to my spam folder. I fixed this with commit https://github.com/PreibischLab/BigStitcher/commit/876f427b9ff68aa803298e23e5e162e6b0f5d91c and updated Fiji.

Thanks so much for reporting!
