### ISSUE TITLE
'Bake BDV manual transformation' not available in Stiching mode

### ISSUE THREAD

**Issue by lollopus** [PreibischLab/BigStitcher#73]
After viewing the video [https://www.youtube.com/watch?v=TLIGvJYyogI&list=PLNZz8lLDpAeVOeAmQWMrKGOeB3vv28yJE&index=2&t=0s](url) on your YouTube channel I learned the very efficient technique of manual tile alignment using the 't' button followed by BDV shortcuts.

However I quickly noticed that the BAKE command is not available in Stiching mode, but only in Multiview mode. This is unfortunate because BigStitcher allows the user to apply manual transformations in Stitching mode. Thus, one may have spent quite some time and effort in aligning tiles in Stitching mode, only to discover that there's no way to bake them: going into Multiview mode to access the bake command immediatly discards all the tile shifts!

**Comment by StephanPreibisch** [comment]
Hi, sorry for that. The reason is simply that the Stitching mode has efficient ways build in to apply shifts to the datasets (right click > Arrange views). So it seemed confusing to add the BDV transformations as an additional option here, especially since they allow transformations that are beyond translations that affect performance of the automated stitching later on.

**Comment by lollopus** [comment]
Hi and thanks for clarifying the reasons behind this design choice. My suggestion then would be to prevent activation of manual transformation mode in BDV when in Stitching mode (if possible). 

Personally I find the BDV transformations approach significantly more efficient than Arrange views>Manually translate views when working with many disordered low S/R image tiles, even when simply shifting in x,y,z without rotation or scaling.

**Comment by StephanPreibisch** [comment]
Hi, I added the option to BigStitcher (https://github.com/PreibischLab/BigStitcher/commit/2da18414231d89695262cd4b727febf5904b50c8). Please just update Fiji and it'll be available. Would you have time to test if it works as expected, that would be awesome ... :)

**Comment by lollopus** [comment]
Tested and it works.

Thanks for adding the feature!

**Comment by StephanPreibisch** [comment]
great, thanks so much
