### ISSUE TITLE
Dark region after image fusion

### ISSUE THREAD

**Issue by VasylVaskivskyi** [PreibischLab/BigStitcher#82]
This problem appears after running image fusion. BigStitcher creates a black square in the middle of the image.  I also stitched these tiles myself and the result didn't show such an artifact.

<details>
    <summary>This is the result from BigStitcher</summary>

![bsfusion](https://user-images.githubusercontent.com/35797200/99667434-4ead2b80-2a64-11eb-93be-367c36de061f.JPG)

</details>

<details>
    <summary>This what I expect in terms of illumination</summary>

![expected](https://user-images.githubusercontent.com/35797200/99667510-6f758100-2a64-11eb-8919-45079cb9f445.JPG)

</details>

Could this be due to some sort of normalization? 
The input data is uint16 and I also save it as uint16.

<details>
    <summary>This is the fusion settings that I use</summary>

```
    // fuse dataset, save as TIFF
    run("Fuse dataset ...",
        "select=/output/best_focus/Cyc002_Reg001_CH001/dataset.xml" +
        " process_angle=[All angles]" +
        " process_channel=[All channels]" +
        " process_illumination=[All illuminations]" +
        " process_tile=[All tiles]" +
        " process_timepoint=[All Timepoints]" +
        " bounding_box=[All Views]" +
        " downsampling=1" +
        " pixel_type=[16-bit unsigned integer]" +
        " interpolation=[Linear Interpolation]" +
        " image=[Precompute Image]" +
        " interest_points_for_non_rigid=[-= Disable Non-Rigid =-]" +
        " blend produce=[Each timepoint & channel]" +
        " fused_image=[Save as (compressed) TIFF stacks]" +
        " output_file_directory=/output/processed_images/Cyc002_Reg001_CH001");
```
</details>

**Comment by VasylVaskivskyi** [comment]
I can privately send you tiles for this image if you can provide me your email address.

**Comment by StephanPreibisch** [comment]
Hi, this does not look like a bug but an alignment problem that we should try to address by using different parameters for stitching ... is there any way you can share the xml/hdf5 dataset?

**Comment by StephanPreibisch** [comment]
Hi, do you have access to approximate tile locations?

**Comment by StephanPreibisch** [comment]
Was it acquired in a grid?

**Comment by VasylVaskivskyi** [comment]
I don't have tile locations, only number of tiles per row/column and overlap size. They are acquired in a snake fashion: right - down.
Overlap - 30% both ways
Tiles per row - 7
Tiles per column - 9

**Comment by StephanPreibisch** [comment]
Hi, using this info it is rather straight forward to stitch the data. I also converted it to HDF5 first to have interactive feedback. You need to move the tiles to approximate locations first, then run the stitching. Alternatively, you could just exclude tiles with little/no information. I sent you a screen recording how to it.

Best,
Stephan
