### ISSUE TITLE
z layers are not recognized

### ISSUE THREAD

**Issue by saskra** [PreibischLab/BigStitcher#85]
I have a dataset of 2048 x 2048 pixels in 4 x 4 tiles with 3 channels and 132 z slices. Since it looked like BigStitcher couldn't handle the individual z-levels, I stacked them together with a short Python script. But at the end I got an empty black picture. In the attached log file, I noticed the following, so it looked to me as if the z-layers were still causing problems:

```log
Checking z size in file: .../11-16-28_stitchtest_Blaze[02 x 00]_C00_xyz-Table.tif, series 0
Corrected size is 1 (was 132)
```

[Log2.txt](https://github.com/PreibischLab/BigStitcher/files/5628838/Log2.txt)

**Comment by StephanPreibisch** [comment]
Hi, could you try sticking it together with imageJ? Simply drag & drop the folder that contains all slices of a 3d stack into ImageJ/Fiji and resave as 3d tiff?

**Comment by saskra** [comment]
Yes, that helped. But as I had lots of data sets like that I found out how to make Python save it like Fiji does.

**Comment by StephanPreibisch** [comment]
Hi, you can simply use the Fiji Macro Recorder (Plugins > Macro > Record). Should be quite straight forward for such a task ...
