### ISSUE TITLE
SciViewer breaking recent update 

### ISSUE THREAD

**Issue by SinclairRozie** [PreibischLab/BigStitcher#91]
If you have SciViewer active in your Fiji/ImageJ with the most recent BigStitcher update it will not allow you to work with the XML viewer and functions. However, simply uninstalling SciViewer will allow for the BigStitcher Plugin to begin to function correctly again.

**Comment by StephanPreibisch** [comment]
Thanks so much for reporting this, we already encountered that on another problem. SciView is fixing it on their side.
