### ISSUE TITLE
Java Exception during fusion after update

### ISSUE THREAD

**Issue by pawlowska** [PreibischLab/BigStitcher#99]
`java.lang.NoSuchMethodError: net.imglib2.Dimensions.Verify((I)(I ` appears when attempting to fuse and save as new HDF5 project.

![Przechwytywanie](https://user-images.githubusercontent.com/11158300/126462694-bc8939fa-2599-4278-8c9c-ed3667da7894.PNG)

**Comment by StephanPreibisch** [comment]
Hi @pawlowska, I cannot reproduce that error. Might it be that you have other update sites active that replace some imglib2 components with older or newer versions? Could you please try again with only the BigStitcher update site active?

**Comment by pawlowska** [comment]
@StephanPreibisch okay, then this is probably the case. I was trying out some other plugins and activating update sites. In this case I suppose a clean Fiji install will be faster, if I then still have the error, then it will be easier to narrow down.
